#%RAML 0.8
  title: therapy
  baseUri: http://behappy.knbit.edu.pl:14715

  /therapy/therapy.html:
    description: "Main account page, link to new therapy form, list of therapies,
    list of users.Use two get methods for therapy list and for patients list."
